name: Realse and versioning
on:
  push:
    branches:
      - main
      - Development
env:
  PROJECT_PATH: 'TestNuget/TestNuget.csproj'

jobs:
  gitversion:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}


      - name: build
        run: dotnet build  ${{ env.PROJECT_PATH }} 

      - name: build
        run: dotnet test



