name: Realse and versioning
on:
  push:
    paths-ignore:
      - '*.yml'
    branches:
      - main
env:
  PROJECT_PATH: 'TestNuget/TestNuget.csproj'
  PACKAGE_OUTPUT: ${{ github.workspace }}/output
  NUGET_URL: 'https://nuget.npssites.com/nuget/'
  NUGET_PASWORD: ${{ secrets.NUGET_PASWORD }}
  NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}
  NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}

jobs:
  gitversion:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}
      
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          major_pattern: "feat:"
          minor_pattern: "bug:"
          format: "${major}.${minor}.${patch}"


      - name: build
        run: dotnet build  ${{ env.PROJECT_PATH }} --no-restore --configuration Release --version-suffix ${{ steps.versioning.outputs.version }}

      - name: Unit Tests
        run: dotnet test

      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: v${{ steps.versioning.outputs.version }}
          release_name: v${{ steps.versioning.outputs.version }}
          prerelease: false

      - name: Pack
        run: dotnet pack  ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --output ${{ env.PACKAGE_OUTPUT }} --include-symbols -p:PackageVersion=${{ steps.versioning.outputs.version }}

      - name: "Add source"
        run: dotnet nuget add source https://nuget.npssites.com/nuget/ -n "newpark nuget" -u ${{ env.NUGET_USERNAME }} -p "${{ env.NUGET_PASSWORD }}" --store-password-in-clear-text

      - name: Push
        run: dotnet nuget push /home/runner/work/Versioning_Test/Versioning_Test/output/*.nupkg -k ${{ env.NUGET_PASWORD }} -s https://nuget.npssites.com/nuget/ --skip-duplicate
