name: Realse and versioning
on:
  push:
    branches:
      - main

env:
  PROJECT_PATH: 'TestNuget/TestNuget.csproj'
  PACKAGE_OUTPUT: ${{ github.workspace }}/output
  NUGET_URL: 'https://nuget.npssites.com/nuget/'
  NUGET_PASWORD: ${{ secrets.NUGET_PASWORD }}

jobs:
  gitversion:
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all commits
          fetch-depth: 0

      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: build
        run: dotnet build  ${{ env.PROJECT_PATH }} --no-restore --configuration Release

        
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "feat:"
          minor_pattern: "chore:"
          format: "v${major}.${minor}.${patch}"

      - name: Create Release
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: ${{ steps.versioning.outputs.version }}
          prerelease: false

      - name: pack
        run: dotnet pack  ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.versioning.outputs.version }} --output ${{ env.PACKAGE_OUTPUT }}

      - name: Push
        run: dotnet nuget push /home/runner/work/Versioning_Test/Versioning_Test/output/*.nupkg -k BSQ9cfpZz3vmuyWvHatDVJ2 -s https://nuget.npssites.com/nuget/

